title: 'Minh Duc Hoang' 
author: 
        name: 'Minh Duc Hoang'
        url: "https://minhduchoang301.github.io/" 
        email: 'minhduc.hoang@mail.utoronto.ca'
        github: 'https://github.com/minhduchoang301'
        linkedin: 'https://www.linkedin.com/in/minh-duc-hoang-437ab3160/'
description: >- 
        Third-year Computer Science student at UofT  
baseurl: "" 

# github:
#         repo: https://github.com/minhduchoang301

markdown: kramdown
remote_theme: pages-themes/minimal

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
