title: 'Minh Duc Hoang' 
author: 
        name: 'Minh Duc Hoang'
        url: "https://minhduchoang301.github.io/" 
        email: 'dhoang3001@gmail.com'
        github: 'https://github.com/minhduchoang301'
        linkedin: 'https://www.linkedin.com/in/minhduc-hoang/'
description: >- 
        ML Enthusiast  
baseurl: "" 

# github:
#         repo: https://github.com/minhduchoang301

markdown: kramdown
remote_theme: fongandrew/hydeout

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
