title: 'Minh Duc Hoang' 
author: 
        name: 'Minh Duc Hoang'
        url: "https://minhduchoang301.github.io/" 
        email: 'minhduc.hoang@mail.utoronto.ca'
        github: 'https://github.com/minhduchoang301'
        linkedin: 'https://www.linkedin.com/in/my-duc-tran-2341a8191/'
description: >- 
        Third-year HBSc Computer Science at UofT  
baseurl: "" 

# github:
#         repo: https://github.com/minhduchoang301

markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-remote-theme