title: 'Minh Duc Hoang' 
author: 
        name: 'Minh Duc Hoang'
        url: "https://minhduchoang301.github.io/" 
        email: 'minhduc.hoang@mail.utoronto.ca'
        github: 'https://github.com/minhduchoang301'
        linkedin: 'https://www.linkedin.com/in/minh-duc-hoang-437ab3160/'
description: >- 
        Third-year HBSc Computer Science at UofT  
baseurl: "" 

# github:
#         repo: https://github.com/minhduchoang301

markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-remote-theme
  